In [1]:
import normalization as nrm
import pandas as pd

In [2]:
#import imaging data
roi_df = pd.read_csv("C:/Users/mclaughlin.aj/Documents/AM_ANALYSIS/CellProfiler_190212/BM_AM_180808_190312_Results.csv")
roi_df.head(5)

,image,ind cell index,total cell index,Area,Circ.,AR,Round,Solidity,Pax6_mean,Islet1_mean,...,SCGN_median,Kv2.2_median,DAPI3_median,CAVIII_median,Rec_median,DAPI4_median,Calb_median,PKC_median,Parv_median,DAPI5_median
0,21_s1m1,0,0,0.047,0.458,1.551,0.645,0.795,1093.606,1237.738,...,545,2559,432,2216,14732,363,1005,911,554,383
1,21_s1m1,1,1,0.032,0.868,1.462,0.684,0.916,389.737,1787.737,...,505,2325,1421,2063,3089,566,625,901,485,2563
2,21_s1m1,2,2,0.037,0.871,1.156,0.865,0.912,436.575,1095.472,...,1934,2564,2181,2039,2349,578,618,664,304,3695
3,21_s1m1,3,3,0.044,0.709,1.674,0.597,0.879,576.280,1651.413,...,348,2414,3377,1760,1433,799,676,729,247,6672
4,21_s1m1,4,4,0.037,0.658,1.233,0.811,0.787,462.293,1785.806,...,435,2516,1796,1804,1312,432,618,745,275,2477

In [10]:
#calculate mean intensities across slices
nrm.meanSTD(roi_df, ["Pax6_stddev", "CABP5_stddev", "DAPI2_stddev"], 5)

    slide           col        mean         std
1   23_s1  CABP5_stddev  303.896935  225.755282
4   21_s1  CABP5_stddev  207.262796  290.696659
7   21_s2  CABP5_stddev  139.089397  117.583686
10  23_s2  CABP5_stddev  297.327157  248.312573
2   23_s1  DAPI2_stddev  145.624023  139.453652
5   21_s1  DAPI2_stddev  175.139843  167.296824
8   21_s2  DAPI2_stddev  108.365552  101.797622
11  23_s2  DAPI2_stddev  123.577231  121.813099
0   23_s1   Pax6_stddev  201.020837  118.516001
3   21_s1   Pax6_stddev  199.912903  113.337644
6   21_s2   Pax6_stddev  158.398753   82.381453
9   23_s2   Pax6_stddev  221.067262  297.666798

In [9]:
#calculates mean of the whole data set to determine the center point to normalize to
totalMean=nrm.meanSTD(roi_df, ["Pax6_stddev", "CABP5_mean", "DAPI2_mean"], 1)
totalMean

  slide         col         mean          std
1     2  CABP5_mean  2732.730635  1099.339962
2     2  DAPI2_mean  1046.392816   710.115275
0     2   Pax6_mean  1122.112810   481.418647

In [ ]:
#take each raw value (row) and divide it by its respective mean. This will put everything on 0-1 scale
#then multiply all rows by the relevant totalMean[mean] to center them on a relevant intensity value